name: derivative-base
channels:
  - conda-forge
  - pytorch
  - nodefaults
dependencies:
  - python=3.8.*
  - mamba
  - poetry=1.*
  - beautifulsoup4=4.9.3
  - blpapi=3.16.2
  - bokeh=2.3.0
  - bottleneck=1.3.2
  - cryptography=3.4.7
  - cx_Oracle=8.1.0
  - cython=0.29.22
  - dask=2021.3.1
  - datashape=0.5.4
  - decorator=4.4.2
  - dill=0.3.3
  - dtreeviz=1.2
  - graphviz=2.47.0
  - img2pdf=0.3.6
  - ipykernel=5.5.0
  - ipython=7.20.0
  - ipywidgets=7.6.3
  - jdcal=1.4.1
  - jedi=0.18.0
  - joblib=1.0.1
  - matplotlib=3.4.1
  - more-itertools=8.7.0
  - mpmath=1.2.1
  - networkx=2.5
  - numexpr=2.7.3
  - numpy=1.20.1
  - olefile=0.46
  - openpyxl=3.0.7
  - orange3=3.28.0
  - pandas=1.2.2
  - partd=1.1.0
  - patsy=0.5.1
  - pillow=8.1.2
  - plotly=4.14.3
  - ptyprocess=0.7.0
  - pymc3=3.11.2
  - pypdf2=1.26.0
  - pyqtgraph=0.12.0
  - python-dateutil=2.8.1
  - pytz=2021.1
  - requests=2.25.1
  - scikit-image=0.18.1
  - scikit-learn=0.24.1
  - scipy=1.6.2
  - seaborn=0.11.1
  - statsmodels=0.12.2
  - sympy=1.7.1
  - ta-lib=0.4.19
  - tensorflow=2.4.1
  - tensorboard==2.4.1
  - tensorboard-plugin-wit==1.8.0
  - theano=1.0.5
  - toolz=0.11.1
  - unicodecsv=0.14.1
  - xlrd=2.0.1
  - xlsxWriter=1.3.8
  - xlwt=1.3
  - torchvision==0.8.2
  - torchaudio==0.7.2
  - pytorch=1.7.1
platforms:
  - linux-64
